### ISSUE TITLE
xtarfile.open does not support encoding option

### ISSUE THREAD

**Issue by jelly** [ascoderu/xtarfile#3]
For example the following code is not supported:
```
tarfile.open(package, mode='r', encoding='utf-8')
```

**Comment by c-w** [comment]
Thanks for reporting the issue. Could you provide some steps to reproduce the behavior?

Currently `xtarfile.open` captures extra arguments and passes them to the underlying compressors such as TarFile (see [code](https://github.com/ascoderu/xtarfile/blob/3e152c26afc7a59969e4cc3a7ae72b3b970f64b4/xtarfile/xtarfile.py#L34) and [list of supported arguments](https://github.com/python/cpython/blob/e02ab59fdffa0bb841182c30ef1355c89578d945/Lib/tarfile.py#L1439-L1450)) or ZStandard (see [code](https://github.com/ascoderu/xtarfile/blob/3e152c26afc7a59969e4cc3a7ae72b3b970f64b4/xtarfile/xtarfile.py#L38) and [list of supported arguments](https://github.com/indygreg/python-zstandard/tree/7708398b211267d686edda89fb960d8ffc47ff6f#zstddecompressor)). What is the behavior you'd expect in this situation?

**Comment by jelly** [comment]
Hmm not sure what is expected, for use case we actually managed to be able to remove the encoding argument and keep it working.

Feel free to close the issue.
